openapi: 3.0.3
info:
  version: 1.0.0
  title: Harmoniq API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Harmoniq app
tags:
  - name: Articles
    description: Operations about articles.
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Operations about users.
servers:
  - url: https://harmoniq-server-big-team.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'

  /articles:
    post:
      $ref: '../swagger/paths/articles/post.yaml'
    get:
      $ref: '../swagger/paths/articles/get.yaml'
  /articles/{articleId}:
    get:
      $ref: '../swagger/paths/articles/{articleId}/get.yaml'
    patch:
      $ref: '../swagger/paths/articles/{articleId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/articles/{articleId}/delete.yaml'

  /users:
    get:
      $ref: '../swagger/paths/users/getAllUsers.yaml'
  /users/{userId}:
    get:
      $ref: '../swagger/paths/users/{userId}/getUserById.yaml'
    patch:
      $ref: '../swagger/paths/users/{userId}/patchUser.yaml'
  /users/{userId}/saved-articles:
    get:
      $ref: '../swagger/paths/users/{userId}/getSavedArticlesById.yaml'
  /users/{userId}/saved-articles/{articleId}:
    post:
      $ref: '../swagger/paths/users/postSavedArticlesById.yaml'
    delete:
      $ref: '../swagger/paths/users/deleteSavedArticlesById.yaml'
  /users/{userId}/articles:
    get:
      $ref: '../swagger/paths/users/getArticlesById.yaml'
  /users/{userId}/avatar:
    post:
      $ref: '../swagger/paths/users/postUserPhoto.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    users:
      $ref: ../swagger/components/schemas/users.yaml
    article:
      $ref: '../swagger/components/schemas/article.yaml'
  responses:
    UnauthorizedError:
      $ref: '../swagger/components/responses/401.yaml'
    NotFoundError:
      $ref: '../swagger/components/responses/404.yaml'
